ssoServiceUrl: https://uaa.local.pcfdev.io

spring:
  thymeleaf:
    cache: false
security:
  oauth2:
    client:
      client-id: client1
      client-secret: client1
      access-token-uri: ${ssoServiceUrl}/oauth/token
      user-authorization-uri: ${ssoServiceUrl}/oauth/authorize
    resource:
      jwt:
        key-uri: ${ssoServiceUrl}/token_key
      user-info-uri: ${ssoServiceUrl}/userinfo

logging.level:
  org.springframework.security: INFO